from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors

from reportlab.platypus import HRFlowable



def create_pdf(file_path, match_score, ats_score, skills, missing, suggestions):

    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()

    content = []

    # -------------------Section Divider-------------------
    content.append(HRFlowable(width="100%", thickness=1, color=colors.grey))

    # ------------------ TITLE ------------------
    content.append(Paragraph("<b><font size=18>AI Resume Analysis Report</font></b>", styles["Title"]))
    content.append(Spacer(1, 20))

    # ------------------ SCORES ------------------
    content.append(Paragraph(
    f"<b><font color='green'>Match Score:</font></b> {match_score}%",
    styles["Heading2"]
    ))
    content.append(Paragraph(
        f"<b><font color='blue'>ATS Score:</font></b> {ats_score}%",
        styles["Heading2"]
    ))
    content.append(Spacer(1, 15))

    # ------------------ SKILLS ------------------
    content.append(Paragraph("<b>Extracted Skills</b>", styles["Heading2"]))
    skill_list = ListFlowable(
        [Paragraph(skill, styles["Normal"]) for skill in skills],
        bulletType='bullet'
    )
    content.append(skill_list)
    content.append(Spacer(1, 15))

    # ------------------ MISSING SKILLS ------------------
    content.append(Paragraph("<b>Missing Skills</b>", styles["Heading2"]))
    missing_list = ListFlowable(
        [Paragraph(skill, styles["Normal"]) for skill in missing],
        bulletType='bullet'
    )
    content.append(missing_list)
    content.append(Spacer(1, 15))

    # ------------------ AI SUGGESTIONS ------------------
    content.append(Paragraph("<b>AI Suggestions</b>", styles["Heading2"]))
    content.append(Spacer(1, 10))

    lines = suggestions.split("\n")

    bullet_items = []

    for line in lines:
        line = line.strip()

        if not line:
            continue

        # Detect headings (lines ending with :)
        if line.endswith(":"):
            content.append(Spacer(1, 8))
            content.append(Paragraph(f"<b>{line}</b>", styles["Heading3"]))
            content.append(Spacer(1, 5))

        # Detect bullet points
        elif line.startswith("-") or line.startswith("•"):
            bullet_items.append(Paragraph(line[1:].strip(), styles["Normal"]))

        else:
            # Normal paragraph
            content.append(Paragraph(line, styles["Normal"]))
            content.append(Spacer(1, 5))

    # Add bullet list if exists
    if bullet_items:
        content.append(ListFlowable(bullet_items, bulletType='bullet'))

        
    # ------------------ FOOTER ------------------
    content.append(Paragraph(
        "<font size=10 color=grey>Generated by AI Resume Analyzer</font>",
        styles["Normal"]
    ))

    # Build PDF
    doc.build(content)